/**
 * localhost:8088
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AsteriskPing model module.
* @module model/AsteriskPing
* @version 6.0.0
*/
export default class AsteriskPing {
    /**
    * Constructs a new <code>AsteriskPing</code>.
    * Asterisk ping information
    * @alias module:model/AsteriskPing
    * @class
    * @param asteriskId {String} Asterisk id info
    * @param ping {String} Always string value is pong
    * @param timestamp {String} The timestamp string of request received time
    */

    constructor(asteriskId, ping, timestamp) {
        
        
        this['asterisk_id'] = asteriskId;
        this['ping'] = ping;
        this['timestamp'] = timestamp;
        
    }

    /**
    * Constructs a <code>AsteriskPing</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AsteriskPing} obj Optional instance to populate.
    * @return {module:model/AsteriskPing} The populated <code>AsteriskPing</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AsteriskPing();
                        
            
            if (data.hasOwnProperty('asterisk_id')) {
                obj['asterisk_id'] = ApiClient.convertToType(data['asterisk_id'], 'String');
            }
            if (data.hasOwnProperty('ping')) {
                obj['ping'] = ApiClient.convertToType(data['ping'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
        }
        return obj;
    }

    /**
    * Asterisk id info
    * @member {String} asterisk_id
    */
    'asterisk_id' = undefined;
    /**
    * Always string value is pong
    * @member {String} ping
    */
    'ping' = undefined;
    /**
    * The timestamp string of request received time
    * @member {String} timestamp
    */
    'timestamp' = undefined;




}
