/**
 * localhost:8088
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Binary model module.
* @module model/Binary
* @version 6.0.0
*/
export default class Binary {
    /**
    * Constructs a new <code>Binary</code>.
    * Binary
    * @alias module:model/Binary
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Binary</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Binary} obj Optional instance to populate.
    * @return {module:model/Binary} The populated <code>Binary</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Binary();
                        
            
        }
        return obj;
    }





}
