/**
 * localhost:8088
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CallerID model module.
* @module model/CallerID
* @version 6.0.0
*/
export default class CallerID {
    /**
    * Constructs a new <code>CallerID</code>.
    * Caller identification
    * @alias module:model/CallerID
    * @class
    * @param name {String} 
    * @param _number {String} 
    */

    constructor(name, _number) {
        
        
        this['name'] = name;
        this['number'] = _number;
        
    }

    /**
    * Constructs a <code>CallerID</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CallerID} obj Optional instance to populate.
    * @return {module:model/CallerID} The populated <code>CallerID</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CallerID();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} number
    */
    'number' = undefined;




}
