/**
 * Asterisk ARI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Containers model module.
* @module model/Containers
* @version 6.0.0
*/
export default class Containers {
    /**
    * Constructs a new <code>Containers</code>.
    * Container
    * @alias module:model/Containers
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Containers</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Containers} obj Optional instance to populate.
    * @return {module:model/Containers} The populated <code>Containers</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Containers();
                        
            
        }
        return obj;
    }





}
