/**
 * Asterisk ARI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The DeviceState model module.
* @module model/DeviceState
* @version 6.0.0
*/
export default class DeviceState {
    /**
    * Constructs a new <code>DeviceState</code>.
    * Represents the state of a device.
    * @alias module:model/DeviceState
    * @class
    * @param name {String} Name of the device.
    * @param state {String} Device's state
    */

    constructor(name, state) {
        
        
        this['name'] = name;
        this['state'] = state;
        
    }

    /**
    * Constructs a <code>DeviceState</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DeviceState} obj Optional instance to populate.
    * @return {module:model/DeviceState} The populated <code>DeviceState</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeviceState();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }

    /**
    * Name of the device.
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Device's state
    * @member {String} state
    */
    'state' = undefined;




}
