/**
 * localhost:8088
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The DialplanCEP model module.
* @module model/DialplanCEP
* @version 6.0.0
*/
export default class DialplanCEP {
    /**
    * Constructs a new <code>DialplanCEP</code>.
    * Dialplan location (context/extension/priority)
    * @alias module:model/DialplanCEP
    * @class
    * @param appData {String} Parameter of current dialplan application
    * @param appName {String} Name of current dialplan application
    * @param context {String} Context in the dialplan
    * @param exten {String} Extension in the dialplan
    * @param priority {Number} Priority in the dialplan
    */

    constructor(appData, appName, context, exten, priority) {
        
        
        this['app_data'] = appData;
        this['app_name'] = appName;
        this['context'] = context;
        this['exten'] = exten;
        this['priority'] = priority;
        
    }

    /**
    * Constructs a <code>DialplanCEP</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DialplanCEP} obj Optional instance to populate.
    * @return {module:model/DialplanCEP} The populated <code>DialplanCEP</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DialplanCEP();
                        
            
            if (data.hasOwnProperty('app_data')) {
                obj['app_data'] = ApiClient.convertToType(data['app_data'], 'String');
            }
            if (data.hasOwnProperty('app_name')) {
                obj['app_name'] = ApiClient.convertToType(data['app_name'], 'String');
            }
            if (data.hasOwnProperty('context')) {
                obj['context'] = ApiClient.convertToType(data['context'], 'String');
            }
            if (data.hasOwnProperty('exten')) {
                obj['exten'] = ApiClient.convertToType(data['exten'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Parameter of current dialplan application
    * @member {String} app_data
    */
    'app_data' = undefined;
    /**
    * Name of current dialplan application
    * @member {String} app_name
    */
    'app_name' = undefined;
    /**
    * Context in the dialplan
    * @member {String} context
    */
    'context' = undefined;
    /**
    * Extension in the dialplan
    * @member {String} exten
    */
    'exten' = undefined;
    /**
    * Priority in the dialplan
    * @member {Number} priority
    */
    'priority' = undefined;




}
