/**
 * localhost:8088
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The FormatLangPair model module.
* @module model/FormatLangPair
* @version 6.0.0
*/
export default class FormatLangPair {
    /**
    * Constructs a new <code>FormatLangPair</code>.
    * Identifies the format and language of a sound file
    * @alias module:model/FormatLangPair
    * @class
    * @param format {String} 
    * @param language {String} 
    */

    constructor(format, language) {
        
        
        this['format'] = format;
        this['language'] = language;
        
    }

    /**
    * Constructs a <code>FormatLangPair</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FormatLangPair} obj Optional instance to populate.
    * @return {module:model/FormatLangPair} The populated <code>FormatLangPair</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FormatLangPair();
                        
            
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} format
    */
    'format' = undefined;
    /**
    * @member {String} language
    */
    'language' = undefined;




}
