/**
 * localhost:8088
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LiveRecording model module.
* @module model/LiveRecording
* @version 6.0.0
*/
export default class LiveRecording {
    /**
    * Constructs a new <code>LiveRecording</code>.
    * A recording that is in progress
    * @alias module:model/LiveRecording
    * @class
    * @param format {String} Recording format (wav, gsm, etc.)
    * @param name {String} Base name for the recording
    * @param state {String} 
    * @param targetUri {String} URI for the channel or bridge being recorded
    */

    constructor(format, name, state, targetUri) {
        
        
        this['format'] = format;
        this['name'] = name;
        this['state'] = state;
        this['target_uri'] = targetUri;
        
    }

    /**
    * Constructs a <code>LiveRecording</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LiveRecording} obj Optional instance to populate.
    * @return {module:model/LiveRecording} The populated <code>LiveRecording</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LiveRecording();
                        
            
            if (data.hasOwnProperty('cause')) {
                obj['cause'] = ApiClient.convertToType(data['cause'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('silence_duration')) {
                obj['silence_duration'] = ApiClient.convertToType(data['silence_duration'], 'Number');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('talking_duration')) {
                obj['talking_duration'] = ApiClient.convertToType(data['talking_duration'], 'Number');
            }
            if (data.hasOwnProperty('target_uri')) {
                obj['target_uri'] = ApiClient.convertToType(data['target_uri'], 'String');
            }
        }
        return obj;
    }

    /**
    * Cause for recording failure if failed
    * @member {String} cause
    */
    'cause' = undefined;
    /**
    * Duration in seconds of the recording
    * @member {Number} duration
    */
    'duration' = undefined;
    /**
    * Recording format (wav, gsm, etc.)
    * @member {String} format
    */
    'format' = undefined;
    /**
    * Base name for the recording
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Duration of silence, in seconds, detected in the recording. This is only available if the recording was initiated with a non-zero maxSilenceSeconds.
    * @member {Number} silence_duration
    */
    'silence_duration' = undefined;
    /**
    * @member {String} state
    */
    'state' = undefined;
    /**
    * Duration of talking, in seconds, detected in the recording. This is only available if the recording was initiated with a non-zero maxSilenceSeconds.
    * @member {Number} talking_duration
    */
    'talking_duration' = undefined;
    /**
    * URI for the channel or bridge being recorded
    * @member {String} target_uri
    */
    'target_uri' = undefined;




}
