/**
 * localhost:8088
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Mailbox model module.
* @module model/Mailbox
* @version 6.0.0
*/
export default class Mailbox {
    /**
    * Constructs a new <code>Mailbox</code>.
    * Represents the state of a mailbox.
    * @alias module:model/Mailbox
    * @class
    * @param name {String} Name of the mailbox.
    * @param newMessages {Number} Count of new messages in the mailbox.
    * @param oldMessages {Number} Count of old messages in the mailbox.
    */

    constructor(name, newMessages, oldMessages) {
        
        
        this['name'] = name;
        this['new_messages'] = newMessages;
        this['old_messages'] = oldMessages;
        
    }

    /**
    * Constructs a <code>Mailbox</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Mailbox} obj Optional instance to populate.
    * @return {module:model/Mailbox} The populated <code>Mailbox</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Mailbox();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('new_messages')) {
                obj['new_messages'] = ApiClient.convertToType(data['new_messages'], 'Number');
            }
            if (data.hasOwnProperty('old_messages')) {
                obj['old_messages'] = ApiClient.convertToType(data['old_messages'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Name of the mailbox.
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Count of new messages in the mailbox.
    * @member {Number} new_messages
    */
    'new_messages' = undefined;
    /**
    * Count of old messages in the mailbox.
    * @member {Number} old_messages
    */
    'old_messages' = undefined;




}
