/**
 * localhost:8088
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Module model module.
* @module model/Module
* @version 6.0.0
*/
export default class Module {
    /**
    * Constructs a new <code>Module</code>.
    * Details of an Asterisk module
    * @alias module:model/Module
    * @class
    * @param description {String} The description of this module
    * @param name {String} The name of this module
    * @param status {String} The running status of this module
    * @param supportLevel {String} The support state of this module
    * @param useCount {Number} The number of times this module is being used
    */

    constructor(description, name, status, supportLevel, useCount) {
        
        
        this['description'] = description;
        this['name'] = name;
        this['status'] = status;
        this['support_level'] = supportLevel;
        this['use_count'] = useCount;
        
    }

    /**
    * Constructs a <code>Module</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Module} obj Optional instance to populate.
    * @return {module:model/Module} The populated <code>Module</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Module();
                        
            
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('support_level')) {
                obj['support_level'] = ApiClient.convertToType(data['support_level'], 'String');
            }
            if (data.hasOwnProperty('use_count')) {
                obj['use_count'] = ApiClient.convertToType(data['use_count'], 'Number');
            }
        }
        return obj;
    }

    /**
    * The description of this module
    * @member {String} description
    */
    'description' = undefined;
    /**
    * The name of this module
    * @member {String} name
    */
    'name' = undefined;
    /**
    * The running status of this module
    * @member {String} status
    */
    'status' = undefined;
    /**
    * The support state of this module
    * @member {String} support_level
    */
    'support_level' = undefined;
    /**
    * The number of times this module is being used
    * @member {Number} use_count
    */
    'use_count' = undefined;




}
