/**
 * Asterisk ARI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SetId model module.
* @module model/SetId
* @version 6.0.0
*/
export default class SetId {
    /**
    * Constructs a new <code>SetId</code>.
    * Effective user/group id
    * @alias module:model/SetId
    * @class
    * @param group {String} Effective group id.
    * @param user {String} Effective user id.
    */

    constructor(group, user) {
        
        
        this['group'] = group;
        this['user'] = user;
        
    }

    /**
    * Constructs a <code>SetId</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SetId} obj Optional instance to populate.
    * @return {module:model/SetId} The populated <code>SetId</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetId();
                        
            
            if (data.hasOwnProperty('group')) {
                obj['group'] = ApiClient.convertToType(data['group'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
        }
        return obj;
    }

    /**
    * Effective group id.
    * @member {String} group
    */
    'group' = undefined;
    /**
    * Effective user id.
    * @member {String} user
    */
    'user' = undefined;




}
