/**
 * Asterisk ARI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The StatusInfo model module.
* @module model/StatusInfo
* @version 6.0.0
*/
export default class StatusInfo {
    /**
    * Constructs a new <code>StatusInfo</code>.
    * Info about Asterisk status
    * @alias module:model/StatusInfo
    * @class
    * @param lastReloadTime {Date} Time when Asterisk was last reloaded.
    * @param startupTime {Date} Time when Asterisk was started.
    */

    constructor(lastReloadTime, startupTime) {
        
        
        this['last_reload_time'] = lastReloadTime;
        this['startup_time'] = startupTime;
        
    }

    /**
    * Constructs a <code>StatusInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StatusInfo} obj Optional instance to populate.
    * @return {module:model/StatusInfo} The populated <code>StatusInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatusInfo();
                        
            
            if (data.hasOwnProperty('last_reload_time')) {
                obj['last_reload_time'] = ApiClient.convertToType(data['last_reload_time'], 'Date');
            }
            if (data.hasOwnProperty('startup_time')) {
                obj['startup_time'] = ApiClient.convertToType(data['startup_time'], 'Date');
            }
        }
        return obj;
    }

    /**
    * Time when Asterisk was last reloaded.
    * @member {Date} last_reload_time
    */
    'last_reload_time' = undefined;
    /**
    * Time when Asterisk was started.
    * @member {Date} startup_time
    */
    'startup_time' = undefined;




}
