/**
 * localhost:8088
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The StoredRecording model module.
* @module model/StoredRecording
* @version 6.0.0
*/
export default class StoredRecording {
    /**
    * Constructs a new <code>StoredRecording</code>.
    * A past recording that may be played back.
    * @alias module:model/StoredRecording
    * @class
    * @param format {String} 
    * @param name {String} 
    */

    constructor(format, name) {
        
        
        this['format'] = format;
        this['name'] = name;
        
    }

    /**
    * Constructs a <code>StoredRecording</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StoredRecording} obj Optional instance to populate.
    * @return {module:model/StoredRecording} The populated <code>StoredRecording</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoredRecording();
                        
            
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} format
    */
    'format' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;




}
