/**
 * localhost:8088
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SystemInfo model module.
* @module model/SystemInfo
* @version 6.0.0
*/
export default class SystemInfo {
    /**
    * Constructs a new <code>SystemInfo</code>.
    * Info about Asterisk
    * @alias module:model/SystemInfo
    * @class
    * @param entityId {String} 
    * @param version {String} Asterisk version.
    */

    constructor(entityId, version) {
        
        
        this['entity_id'] = entityId;
        this['version'] = version;
        
    }

    /**
    * Constructs a <code>SystemInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SystemInfo} obj Optional instance to populate.
    * @return {module:model/SystemInfo} The populated <code>SystemInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SystemInfo();
                        
            
            if (data.hasOwnProperty('entity_id')) {
                obj['entity_id'] = ApiClient.convertToType(data['entity_id'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} entity_id
    */
    'entity_id' = undefined;
    /**
    * Asterisk version.
    * @member {String} version
    */
    'version' = undefined;




}
