/**
 * localhost:8088
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import Sound from '../model/Sound';

/**
* Sounds service.
* @module api/SoundsApi
* @version 6.0.0
*/
export default class SoundsApi {

    /**
    * Constructs a new SoundsApi. 
    * @alias module:api/SoundsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getsound operation.
     * @callback module:api/SoundsApi~getsoundCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Sound} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a sound&#x27;s details.
     * @param {module:api/SoundsApi~getsoundCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Sound}
     */
    getsound(soundId, callback) {
      let postBody = null;

      let pathParams = {
        'soundId': soundId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Sound;

      return this.apiClient.callApi(
        '/sounds/{soundId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listsounds operation.
     * @callback module:api/SoundsApi~listsoundsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Sound>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all sounds.
     * @param {Object} opts Optional parameters
     * @param {module:api/SoundsApi~listsoundsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Sound>}
     */
    listsounds(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'lang': opts['lang'],
        'format': opts['format']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [Sound];

      return this.apiClient.callApi(
        '/sounds', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
