/**
 * Asterisk ARI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsteriskAri);
  }
}(this, function(expect, AsteriskAri) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsteriskAri.ContactInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContactInfo', function() {
    it('should create an instance of ContactInfo', function() {
      // uncomment below and update the code to test ContactInfo
      //var instane = new AsteriskAri.ContactInfo();
      //expect(instance).to.be.a(AsteriskAri.ContactInfo);
    });

    it('should have the property aor (base name: "aor")', function() {
      // uncomment below and update the code to test the property aor
      //var instane = new AsteriskAri.ContactInfo();
      //expect(instance).to.be();
    });

    it('should have the property contactStatus (base name: "contact_status")', function() {
      // uncomment below and update the code to test the property contactStatus
      //var instane = new AsteriskAri.ContactInfo();
      //expect(instance).to.be();
    });

    it('should have the property roundtripUsec (base name: "roundtrip_usec")', function() {
      // uncomment below and update the code to test the property roundtripUsec
      //var instane = new AsteriskAri.ContactInfo();
      //expect(instance).to.be();
    });

    it('should have the property uri (base name: "uri")', function() {
      // uncomment below and update the code to test the property uri
      //var instane = new AsteriskAri.ContactInfo();
      //expect(instance).to.be();
    });

  });

}));
